version: "3"

networks:
  nginx:
    external: true
  vpn:
    external: true

volumes:
  npm:
  portainer:

services:
  #################################################################
  #       NGINX PROXY MANAGER
  #################################################################
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    env_file:
      - ./tz.env
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    volumes:
      - npm:/data
      - ~/.certs/nginx:/certs
    networks:
      - nginx
  #################################################################
  #       PORTAINER - CONTAINER MANAGEMENT
  #################################################################
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    env_file:
      - ./tz.env
    ports:
      - 8000:8000
      - 9443:9443
      - 9000:9000
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - nginx
  #################################################################
  #       GLUETUN - VPN
  #################################################################
  vpn:
    image: qmcgaw/gluetun
    container_name: vpn
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 9797:9797 #qbittorrent
      - 6881:6881 #qbittorrent
      - 6881:6881/udp #qbittorrent
    volumes:
      - ~/.vpn/config.conf:/gluetun/custom.conf:ro
    env_file:
      - ./tz.env
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - OPENVPN_USER=burak.tabn@gmail.com
      - OPENVPN_PASSWORD=nail199822
    networks:
      - vpn
      - nginx
  #################################################################
  #       QBITTORENT
  #################################################################
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:vpn"
    env_file:
      - ./tz.env
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=9797
    volumes:
      - ~/.qbittorent:/config
      - /media/downloads:/downloads
    depends_on:
      - vpn
    networks:
      - nginx
    restart: unless-stopped