version: "3"

networks:
  nginx:
    external: true

services:
  #################################################################
  #       JELLYFIN
  #################################################################
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: "unless-stopped"
    volumes:
      - /srv/jellyfin/config:/config
      - /srv/jellyfin/cache:/cache
      - /virt/media:/media
      - /media:/media2
    env_file:
      - ./tz.env
    environment:
      - PUID=1000
      - PGID=1000
      - JELLYFIN_PublishedServerUrl=https://jelllyfin.buraktaban.ca
    ports:
      - 8096:8096
    networks:
      - nginx
  #################################################################
  #       RADARR
  #################################################################
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    env_file:
      - ./tz.env
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./.radarr:/config
      - /virt/media/movies:/movies #optional
      - /media/movies:/moveis2
      - /media/downloads:/downloads #optional
    ports:
      - 7878:7878
    networks:
      - vpn
      - nginx
  #################################################################
  #       JACKETT
  #################################################################
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    restart: unless-stopped
    env_file:
      - ./tz.env
    environment:
      - PUID=1000
      - PGID=1000
      - AUTO_UPDATE=true #optional
      - RUN_OPTS=<run options here> #optional
    volumes:
      - ./.jackett:/config
      - /media/downloads:/downloads
    ports:
      - 9117:9117
    networks:
      - nginx
  #################################################################
  #       SONARR
  #################################################################
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    env_file:
      - ./tz.env
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./.sonarr:/config
      - /virt/media/shows:/tv #optional
      - /media/downloads:/downloads #optional
      - /media/tv/:/tv2
    ports:
      - 8989:8989
    networks:
      - vpn
      - nginx